apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "f1r3fly.fullname" . }}-bonds
  labels: 
    {{- include "f1r3fly.labels" . | nindent 4 }}
data:
  bonds.txt: |
    {{- range $keys := mustSlice $.Values.nodeKeys 0 $.Values.replicaCount }}
    {{ .publicKey }} 50000000000000
    {{- end }}
       