apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "f1r3fly.fullname" . }}-common
  labels:
    {{- include "f1r3fly.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "configs/common/*").AsConfig | indent 2 }}
