{{/* Creates separate PersistentVolumeClaim for each StatefulSet */}}
{{- $deployableReplicas := int64 .Values.shardConfig.deployableReplicas }}
{{- $readOnlyReplicas := int64 .Values.shardConfig.readOnlyReplicas }}
{{- $totalReplicas := int (add $deployableReplicas $readOnlyReplicas) }}
{{- range $index, $e := until $totalReplicas }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "f1r3fly.fullname" $ }}-claim-{{ $index }}
  labels: 
    {{- include "f1r3fly.labels" $ | nindent 4 }}
spec:
  storageClassName: {{ $.Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
{{- end }}
