apiVersion: v1
kind: Service
metadata:
  name: {{ include "f1r3fly.fullname" . }}
  labels:
    {{- include "f1r3fly.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $index, $e := until (int .Values.replicaCount) }}
    {{- range $port := $.Values.service.ports }}
    - name: {{ $port.containerPort }}-{{ $index }}
      targetPort: {{ $port.containerPort | toString }}
      port: {{ $port.containerPort }}
      containerPort: {{ $port.containerPort }}
      protocol: TCP
      {{- if eq $.Values.service.type "NodePort" }}
      {{- /* 
      Creates custom NodePort for each Container Port
      by tempalte "404(replica count index)(last number from container port)"
      
      Example:
      - 40402 for 1th replica => 40412
      - 40402 for 0th replica => 40402
      - 40402 for 9th replica => 40492
      
      Limitation: supports 1-10 replicas only
      */}}
      
      {{- $nodePort := printf "404%s%s" ($index | toString) (trunc -1 ($port.containerPort | toString)) }}  
      nodePort: {{ $nodePort }}
      {{- end }}
    {{- end }}
  {{- end }}
  selector:
    {{- include "f1r3fly.selectorLabels" . | nindent 4 }}
