{{/* Creates separate StatefulSets */}}
{{- $totalReplicas := int (add $.Values.shardConfig.deployableReplicas $.Values.shardConfig.readOnlyReplicas) }}
{{- $deployableReplicas := int $.Values.shardConfig.deployableReplicas }}
{{- range $index, $e := until $totalReplicas }}
{{- $isObserverNode := ge $index $deployableReplicas }}
{{- $isBootstrapNode := eq $index 0 }}
{{- $configMapType := ternary "observer" "deployable" $isObserverNode }}
{{- $configMapName := printf "%s-%s-rnode-%d" $configMapType (include "f1r3fly.fullname" $) $index }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "f1r3fly.fullname" $ }}{{ $index }}
  labels:
    node: {{ include "f1r3fly.fullname" $ }}{{ $index }}
    {{- include "f1r3fly.labels" $ | nindent 4 }}
spec:
  serviceName: {{ include "f1r3fly.fullname" $ }}{{ $index }}
  {{- if not $.Values.autoscaling.enabled }}
  replicas: 1 # because of N statefulsets
  {{- end }}
  selector:
    matchLabels:
      {{- include "f1r3fly.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with $.Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        node: {{ include "f1r3fly.fullname" $ }}{{ $index }}
        {{- include "f1r3fly.labels" $ | nindent 8 }}
        {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "f1r3fly.serviceAccountName" $ }}
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          args:
            {{- toYaml $.Values.containerArgs | nindent 12 }}
          ports:
          {{- range $port := $.Values.service.ports }}
            - name: {{ $port.containerPort }}-port
              containerPort: {{ $port.containerPort }}
              protocol: TCP
          {{- end }}
          {{/*
          livenessProbe:
            {{- toYaml $.Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.readinessProbe | nindent 12 }}
          */}}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          volumeMounts:
          - name: {{ include "f1r3fly.fullname" $ }}-claim-{{ $index }}
            mountPath: /var/lib/rnode
          - name: {{ $configMapName }}
            mountPath: /var/lib/rnode/rnode.conf
            subPath: rnode.conf
            readOnly: true
          - name:  {{ include "f1r3fly.fullname" $ }}-bonds
            mountPath: /var/lib/rnode/genesis/bonds.txt
            subPath: bonds.txt
            readOnly: true
          - name:  {{ include "f1r3fly.fullname" $ }}-common
            mountPath: /var/lib/rnode/logback.xml
            subPath: logback.xml
            readOnly: true
          - name:  {{ include "f1r3fly.fullname" $ }}-common
            mountPath: /var/lib/rnode/genesis/wallets.txt
            subPath: wallets.txt
            readOnly: true
          {{- if $isBootstrapNode }}
          - name: {{ include "f1r3fly.fullname" $ }}-tls-certs
            mountPath: /var/lib/rnode/node.key.pem
            subPath: node.key.pem
            readOnly: true
          - name: {{ include "f1r3fly.fullname" $ }}-tls-certs
            mountPath: /var/lib/rnode/node.certificate.pem
            subPath: node.certificate.pem
            readOnly: true
          {{- end }}
      volumes:
        - name: {{ include "f1r3fly.fullname" $ }}-claim-{{ $index }}
          persistentVolumeClaim:
            claimName: {{ include "f1r3fly.fullname" $ }}-claim-{{ $index }}
        - name: {{ include "f1r3fly.fullname" $ }}-common
          configMap:
            name: {{ include "f1r3fly.fullname" $ }}-common
        - name: {{ include "f1r3fly.fullname" $ }}-bonds
          configMap:
            name: {{ include "f1r3fly.fullname" $ }}-bonds
        - name: {{ $configMapName }}
          configMap:
            name: {{ $configMapName }}
        {{- if $isBootstrapNode }}
        - name: {{ include "f1r3fly.fullname" $ }}-tls-certs
          secret:
            secretName: {{ include "f1r3fly.fullname" $ }}-tls-certs
        {{- end }}
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
