[workspace]
resolver = "2"
members = [
	"casper",
	"rspace++",
	"rholang",
	"shared",
	"node",
	"node-cli",
	"models",
	"crypto",
	"block-storage",
	"rspace++/libs/rspace_rhotypes",
	"comm"
]

[profile.dev]
debug = true
