apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: boot-claim0
  name: boot-claim0
  namespace: f1r3fly
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
