#apiVersion: apps/v1
#kind: StatefulSet
#metadata:
#  name: f1r3fly-statefulset
#  namespace: f1r3fly
#spec:
#  serviceName: "f1r3fly"
#  replicas: 4
#  selector:
#    matchLabels:
#      app: f1r3fly
#  template:
#    metadata:
#      labels:
#        app: f1r3fly
#    spec:
#      containers:
#        - name: f1r3fly
#          image: rchain/rnode:latest
#          ports:
#            - containerPort: 8080
