apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker/shard.yml convert -o ./docker/k8s/shard/
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: validator2
  name: validator2
  namespace: f1r3fly
spec:
  ports:
    - name: "60400"
      port: 60400
      targetPort: 40400
    - name: "60401"
      port: 60401
      targetPort: 40401
    - name: "60402"
      port: 60402
      targetPort: 40402
    - name: "60403"
      port: 60403
      targetPort: 40403
    - name: "60404"
      port: 60404
      targetPort: 40404
  selector:
    io.kompose.service: validator2
