mod multi_parent_casper_bonding_spec;
mod multi_parent_casper_communication_spec;
mod multi_parent_casper_deploy_spec;
mod multi_parent_casper_finalization_spec;
mod multi_parent_casper_merge_spec;
mod multi_parent_casper_reporting_spec;
mod multi_parent_casper_rholang_spec;
mod multi_parent_casper_smoke_spec;
