blank_issues_enabled: false
contact_links:
  - name: Propose RChain platform improvement (RCHIP)
    url: https://github.com/rchain/rchip-proposals/issues
    about: For RChain platform feature requests, you can consider open an issue on RChain Improvement Proposals repository
  - name: Report security bug
    url: https://docs.google.com/forms/d/1HzG8R0ex122YFYZsmb6QTOv4a0C9i_vwHjB9cpQGjBE
    about: Please report security related bugs here
