version: "3.4"

x-rnode: &default-rnode
  image: ghcr.io/f1r3fly-io/rnode
  user: root
  networks:
    - f1r3fly

services:
  boot:
    <<: *default-rnode
    command:
      [
        "run",
        "--host=$BOOTSTRAP_HOST",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 40400:40400
      - 40401:40401
      - 40402:40402
      - 40403:40403
      - 40404:40404
    volumes:
      - ./data/$BOOTSTRAP_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/bootstrap.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

  validator1:
    <<: *default-rnode
    command:
      [
        "run",
        "--host=$VALIDATOR1_HOST",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 50400:40400
      - 50401:40401
      - 50402:40402
      - 50403:40403
      - 50404:40404
    volumes:
      - ./data/$VALIDATOR1_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/validator1.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

  validator2:
    <<: *default-rnode
    command:
      [
        "run",
        "--host=$VALIDATOR2_HOST",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 60400:40400
      - 60401:40401
      - 60402:40402
      - 60403:40403
      - 60404:40404
    volumes:
      - ./data/$VALIDATOR2_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/validator2.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

  validator3:
    <<: *default-rnode
    command:
      [
        "run",
        "--host=$VALIDATOR3_HOST",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 60500:40400
      - 60501:40401
      - 60502:40402
      - 60503:40403
      - 60504:40404
    volumes:
      - ./data/$VALIDATOR3_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/validator3.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  f1r3fly:




# BOOTSTRAP
# Private key
# 5f668a7ee96d944a4494cc947e4005e172d7ab3461ee5538f1f2a45a835e9657
# Public key
# 04ffc016579a68050d655d55df4e09f04605164543e257c8e6df10361e6068a5336588e9b355ea859c5ab4285a5ef0efdf62bc28b80320ce99e26bb1607b3ad93d
# ETH
# fac7dde9d0fa1df6355bd1382fe75ba0c50e8840
# REV
# 1111AtahZeefej4tvVR6ti9TJtv8yxLebT31SCEVDCKMNikBk5r3g

# Validator_1
# Private key
# 357cdc4201a5650830e0bc5a03299a30038d9934ba4c7ab73ec164ad82471ff9
# Public key
# 04fa70d7be5eb750e0915c0f6d19e7085d18bb1c22d030feb2a877ca2cd226d04438aa819359c56c720142fbc66e9da03a5ab960a3d8b75363a226b7c800f60420
# ETH
# a77c116ce0ebe1331487638233bb52ba6b277da7
# REV
# 111127RX5ZgiAdRaQy4AWy57RdvAAckdELReEBxzvWYVvdnR32PiHA

# Validator_2
# Private key
# 2c02138097d019d263c1d5383fcaddb1ba6416a0f4e64e3a617fe3af45b7851d
# Public key
# 04837a4cff833e3157e3135d7b40b8e1f33c6e6b5a4342b9fc784230ca4c4f9d356f258debef56ad4984726d6ab3e7709e1632ef079b4bcd653db00b68b2df065f
# ETH
# df00c6395a23e9b2b8780de9a93c9522512947c3
# REV
# 111129p33f7vaRrpLqK8Nr35Y2aacAjrR5pd6PCzqcdrMuPHzymczH

# extra
# Private key
# b67533f1f99c0ecaedb7d829e430b1c0e605bda10f339f65d5567cb5bd77cbcb
# Public key
# 0457febafcc25dd34ca5e5c025cd445f60e5ea6918931a54eb8c3a204f51760248090b0c757c2bdad7b8c4dca757e109f8ef64737d90712724c8216c94b4ae661c
# ETH
# ca778c4ecf5c6eb285a86cedd4aaf5167f4eae13
# REV
# 1111LAd2PWaHsw84gxarNx99YVK2aZhCThhrPsWTV7cs1BPcvHftP

# extra
# Private key
# 5ff3514bf79a7d18e8dd974c699678ba63b7762ce8d78c532346e52f0ad219cd
# Public key
# 04d26c6103d7269773b943d7a9c456f9eb227e0d8b1fe30bccee4fca963f4446e3385d99f6386317f2c1ad36b9e6b0d5f97bb0a0041f05781c60a5ebca124a251d
# ETH
# 0cab9328d6d896e5159a1f70bc377e261ded7414
# REV
# 1111La6tHaCtGjRiv4wkffbTAAjGyMsVhzSUNzQxH1jjZH9jtEi3M


