[target.aarch64-unknown-linux-gnu]
pre-build = [
	"dpkg --add-architecture arm64",
	"apt-get update",
	"apt-get install -y protobuf-compiler pkg-config libssl-dev:arm64",
	# https://github.com/sfackler/rust-openssl/issues/2217#issuecomment-2230398481
	"ln -s /usr/include/aarch64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h",
	"ln -s /usr/include/aarch64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h",
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
	"apt-get update && apt-get install -y protobuf-compiler pkg-config libssl-dev",
	# https://github.com/sfackler/rust-openssl/issues/2217#issuecomment-2230398481
	"ln -s /usr/include/x86_64-linux-gnu/openssl/opensslconf.h /usr/include/openssl/opensslconf.h",
	"ln -s /usr/include/x86_64-linux-gnu/openssl/configuration.h /usr/include/openssl/configuration.h",
]
