apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: validator2-claim0
  namespace: f1r3fly-rspaceplusplus
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
