version: "3.4"

x-rnode: &default-rnode
  image: coop.rchain/rnode:latest
  user: root
  networks:
    - f1r3fly

services:
  boot:
    <<: *default-rnode
    container_name: $BOOTSTRAP_HOST
    command:
      [
        "run",
        "-s",
        "--validator-private-key=$BOOTSTRAP_PRIVATE_KEY",
        "--host=$BOOTSTRAP_HOST",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THRESHOLD",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 40400:40400
      - 40401:40401
      - 40402:40402
      - 40403:40403
      - 40404:40404
    volumes:
      - ./data/$BOOTSTRAP_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/bootstrap.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

  validator1:
    <<: *default-rnode
    container_name: $VALIDATOR1_HOST
    command:
      [
        "run",
        "--bootstrap=rnode://138410b5da898936ec1dc13fafd4893950eb191b@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--genesis-validator",
        "--validator-private-key=$VALIDATOR1_PRIVATE_KEY",
        "--host=$VALIDATOR1_HOST",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THRESHOLD",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 50400:40400
      - 50401:40401
      - 50402:40402
      - 50403:40403
      - 50404:40404
    volumes:
      - ./data/$VALIDATOR1_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/validator1.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

  validator2:
    <<: *default-rnode
    container_name: $VALIDATOR2_HOST
    command:
      [
        "run",
        "--bootstrap=rnode://138410b5da898936ec1dc13fafd4893950eb191b@$BOOTSTRAP_HOST?protocol=40400&discovery=40404",
        "--genesis-validator",
        "--validator-private-key=$VALIDATOR2_PRIVATE_KEY",
        "--host=$VALIDATOR2_HOST",
        "--synchrony-constraint-threshold=$SYNCHRONY_CONSTRAINT_THRESHOLD",
        "-Dlogback.configurationFile=/var/lib/rnode/logback.xml"
      ]
    ports:
      - 60400:40400
      - 60401:40401
      - 60402:40402
      - 60403:40403
      - 60404:40404
    volumes:
      - ./data/$VALIDATOR2_HOST:/var/lib/rnode/
      - ./genesis/wallets.txt:/var/lib/rnode/genesis/wallets.txt
      - ./genesis/bonds.txt:/var/lib/rnode/genesis/bonds.txt
      - ./conf/validator2.conf:/var/lib/rnode/rnode.conf
      - ./conf/logback.xml:/var/lib/rnode/logback.xml

networks:
  f1r3fly:
