[package]
name = "bitcoin-anchor"
version = "0.1.0"
edition = "2021"
authors = ["F1r3fly Team"]
description = "Bitcoin L1 anchoring for F1r3fly RSpace state"
license = "MIT OR Apache-2.0"

[dependencies]
# Step 1: Error handling
thiserror = "1.0"

# Step 1: Configuration serialization
serde = { version = "1.0", features = ["derive"] }

# Step 2: Cryptographic hashing for commitments
blake2 = "0.10"
